machine:
  environment:
    PROJECT_GOPATH: /home/erick/app/.circleci
    
dependencies:
  pre:
    - go get -u github.com/erick-ochieng/app/.circleci
    - apt-get install yamllint
  override:
    - mkdir -p /home/erick/app/.circleci
    - rsync -avC /home/erick/app/.circleci
test:
  override:
- cd /home/erick/app/.circle && ./myapp.sh
